const RADIUS_SM = 2;
const RADIUS = 4;
const RADIUS_MD = 6;
const RADIUS_LG = 8;
const RADIUS_2XL = 12;
const RADIUS_FULL = 999;

export { RADIUS_SM, RADIUS, RADIUS_MD, RADIUS_LG, RADIUS_2XL, RADIUS_FULL };
