const RADIUS_SM = 2;
const RADIUS = 4;
const RADIUS_MD = 6;
const RADIUS_LG = 8;
const RADIUS_XL = 10;
const RADIUS_FULL = 999;

export { RADIUS_SM, RADIUS, RADIUS_MD, RADIUS_LG, RADIUS_XL, RADIUS_FULL };
